### ISSUE TITLE
Installer offers no options for customization

### ISSUE THREAD

**Issue by MNeMoNiCuZ** [blib-la/captain#21] opened 2024-01-30 23:20 UTC
**Describe the bug** 
The installer just starts installing the software without the users input

**Expected behavior**
Inform the user of where the program will be installed, and let the user install it wherever they want.
Additionally, there needs to be a functioning CANCEL button, right now you have even disabled the X-button. 
This is beyond scummy and looks very suspicious.
There's no way I let something like this finish installing.

**Screenshots**
![image](https://github.com/blib-la/captain/assets/60541708/c194ea31-b695-4c49-93af-b6a0ca915f8b)

**Comment by pixelass** [comment] 2024-01-31 00:47
Thank you for your input.
This is not a bug but it is noted.
It will be part of the next BETA release.

**Closed** 2024-01-31 11:36 UTC
