### ISSUE TITLE
[BUG]: …Upgrading Captain fails on Windows

### ISSUE THREAD

**Issue by Augustronic** [blib-la/captain#179] opened 2024-03-28 17:13 UTC
**Describe the bug** 
If installing a newer build over an existing installation stops with a message: Captain cannot be closed. Please close it manually and click Retry to continue. But there is no other Captain process running. Can just be canceled.

**Expected behavior**
No interruption.

**Screenshots** 
![image](https://github.com/blib-la/captain/assets/21057489/f088b193-09c5-494f-8524-3d813297f014)

![Screenshot 2024-03-28 182313](https://github.com/blib-la/captain/assets/21057489/cc94987a-afce-4706-86ca-7f4ce68e7fbf)

**Versions (please complete the following information):**

- OS: [e.g. Win11]
- Captain [any]

**Additional context**

**Comment by pixelass** [comment] 2024-03-29 13:52
This should only happen when upgrading from a version that had this issue. It was resolved and should not happen after aplpha.20+ (or so)

It will still occur if the installed version is lower than (whenever this was fixed)

Sorry for the inconvenience See #44

**Comment by pixelass** [comment] 2024-04-27 16:03
We tested this intensively and cannot reproduce this issue anymore (if captain is actually closed)
If this happens, please make sure that Captain is not open anymore (check the system tray)

![image](https://github.com/blib-la/captain/assets/1148334/4495aac3-ef3c-47f6-8eda-b125441eafb5)


Closing as "Cannot reproduce". 
Please feel free to comment if you still encounter this problem.

**Closed as completed by pixelass** 2024-04-27 16:03 UTC

**Comment by cgarrovillo** [comment] 2025-04-15 23:47
Do you have a link to a PR that resolved this issue? This issue is still outstanding for us and could use some help getting pointed in the right direction

**Comment by pixelass** [comment] 2025-04-29 06:45
this project is dead
